name: 'Generate Release Hashes'
author: 'JackMacWindows'
description: 'a'
inputs:
  hash-type:
    description: 'Type of hash to generate (md5, sha1, sha256, sha512)'
    required: false
    default: 'sha256'
  file-name:
    description: 'File name to save as if desired'
    required: false
    default: ''
outputs:
  hashes:
    description: 'A string with the resulting hashes, one per line, with file name followed by hash'
runs:
  using: 'node12'
  main: 'index.js'
